// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwgpqhmypjtwmvlijbzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3Z3BxaG15cGp0d212bGlqYnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDAyMzIsImV4cCI6MjA2OTQ3NjIzMn0.AYB5kImW9uUtLxWwC6FHgfejBrZ-KPmtW0QdD_HzMoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});